// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBfAIf6g7hH0w1gJFjSAGa24MKQTlJg2w',
    appId: '1:562166204765:web:86c885f9867e9d5a8680b4',
    messagingSenderId: '562166204765',
    projectId: 'konterhp-6619a',
    authDomain: 'konterhp-6619a.firebaseapp.com',
    storageBucket: 'konterhp-6619a.firebasestorage.app',
    measurementId: 'G-42YYF61Y3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSi93BR0XNo3SkIToVLh9QL4hyAa71yTc',
    appId: '1:562166204765:android:247e0dd1ce3a8dcd8680b4',
    messagingSenderId: '562166204765',
    projectId: 'konterhp-6619a',
    storageBucket: 'konterhp-6619a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlmAsdgXtywVK9Kcs67yV73fZiqD_cYk4',
    appId: '1:562166204765:ios:5147a60fa73330bf8680b4',
    messagingSenderId: '562166204765',
    projectId: 'konterhp-6619a',
    storageBucket: 'konterhp-6619a.firebasestorage.app',
    iosBundleId: 'com.example.konterhp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlmAsdgXtywVK9Kcs67yV73fZiqD_cYk4',
    appId: '1:562166204765:ios:5147a60fa73330bf8680b4',
    messagingSenderId: '562166204765',
    projectId: 'konterhp-6619a',
    storageBucket: 'konterhp-6619a.firebasestorage.app',
    iosBundleId: 'com.example.konterhp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBfAIf6g7hH0w1gJFjSAGa24MKQTlJg2w',
    appId: '1:562166204765:web:c1e618c3f8704b8b8680b4',
    messagingSenderId: '562166204765',
    projectId: 'konterhp-6619a',
    authDomain: 'konterhp-6619a.firebaseapp.com',
    storageBucket: 'konterhp-6619a.firebasestorage.app',
    measurementId: 'G-6BRV4H22X3',
  );
}
